f = open('rosalind_dna.txt')
s = f.read()
#s = 'TGACCCGATGGGAGCACCCCCAAACATGGCTCCACTCTCGGTAAGAGACAGTTAAACTTCCCCTTTGTGCGTCCTCGACCTGCGTCTGTGAAGCTTGTTTTGTAGTTTGAAGCTAGTAGGAATCGCAGCAAATCTCCCCGACTGGGCTGTGTGAGTTTGCCGATAGGCACGACCGGTCACCAATCCGGACATTACGATCCGGCAAGTATGACAAGTAGAAATTAGTATCCCATGAAACCTAGGTAGGCTTGGAATATTCCTCGTAGCAAGCTGGGCACATGAAATATCTACACACCGTTAAGGTCGCTTCGGTAAAATGTCCTTGGTGATCTTGTTCTACTAGAGTCCCTTCTGATTCTGACTTTAATGCTTAGTCTTTGCGAGCTCGAGGATGTGCGATGGAGCGTTTACCTACTTATGCGCTAAGCAACTTTAGAGGTTCCAGAGACAACCCGTACAGGAAAACGAAGCCACTGTTCACACTTACACCACCGCAAAATCGCCGTCTGTAGGAGAGTCTTAACCGTAATTCACGTATTGAGCTTAGTTCCCGACACCATGATGCCCCTCATCGCATGAACTGACACGCACACACTCATTATCGTCGGTTGCACTGGTTTATTCAGGCTACCACGATGAATTAGTTCAATAAACATGTGTAGCGCTGCACATCCAGATTCGCGCAACATTGCGCAAAGACAATCCACCCATCATCGCAGAATTGACGCCCTGGCGAGCGACCCTCCTAAGCAGATGTCGGCACACCTGGGTGTCTATAGGACCGACCTCTCGAGACGCTTAGCATGAGTGTCAATGG'
Acount = 0
Tcount = 0
Gcount = 0
Ccount = 0
for c in s:
    if c == 'A':
        Acount +=1
    elif c == 'C':
        Ccount +=1
    elif c == 'T':
        Tcount +=1
    elif c == 'G':
        Gcount +=1
print(str(Acount), str(Ccount), str(Gcount), str(Tcount))
f.close()